/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.28-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.or.weather.api;

import java.math.BigDecimal;
import com.or.weather.model.Location;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-06-09T13:14:10.799+03:00")

@Validated
@Api(value = "temperature", description = "the temperature API")
@RequestMapping(value = "")
public interface TemperatureApi {

    @ApiOperation(value = "get current temperature of given location.", nickname = "temperaturePost", notes = "", response = BigDecimal.class, tags={ "Weather", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "current temperature of given location", response = BigDecimal.class),
        @ApiResponse(code = 400, message = "Invalid Location") })
    @RequestMapping(value = "/temperature",
        method = RequestMethod.POST)
    ResponseEntity<BigDecimal> temperaturePost(@ApiParam(value = "Location parameter based on longitude and latitude." ,required=true )  @Valid @RequestBody Location location);

}
